# Generated by Django 3.1.13 on 2021-12-28 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_change_settings_terms_helptext'),
        ('profiles', '0002_auto_20211216_1130'),
    ]

    operations = [
    ]
