# Generated by Django 3.1.14 on 2021-12-24 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20211214_0825'),
        ('profiles', '0002_change_settings_terms_helptext'),
    ]

    operations = [
    ]
