# Generated by Django 3.1.13 on 2021-11-22 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('profiles', '0003_userprofilessettings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfilesSettings',
            new_name='GEUserSettings',
        ),
    ]
