# Generated by Django 3.1.13 on 2021-11-22 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20211122_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geuser',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='geuser',
            name='education_level',
        ),
        migrations.RemoveField(
            model_name='geuser',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='geusersettings',
            name='activate_display_name',
        ),
        migrations.RemoveField(
            model_name='geusersettings',
            name='activate_dob',
        ),
        migrations.RemoveField(
            model_name='geusersettings',
            name='activate_education_level',
        ),
        migrations.RemoveField(
            model_name='geusersettings',
            name='activate_education_level_required',
        ),
        migrations.RemoveField(
            model_name='geusersettings',
            name='activate_gender',
        ),
        migrations.RemoveField(
            model_name='geusersettings',
            name='activate_location',
        ),
        migrations.RemoveField(
            model_name='geusersettings',
            name='capture_display_name_on_reg',
        ),
        migrations.RemoveField(
            model_name='geusersettings',
            name='capture_dob_on_reg',
        ),
        migrations.RemoveField(
            model_name='geusersettings',
            name='capture_education_level_on_reg',
        ),
        migrations.RemoveField(
            model_name='geusersettings',
            name='capture_gender_on_reg',
        ),
        migrations.RemoveField(
            model_name='geusersettings',
            name='capture_location_on_reg',
        ),
        migrations.RemoveField(
            model_name='geusersettings',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='geusersettings',
            name='display_name_required',
        ),
        migrations.RemoveField(
            model_name='geusersettings',
            name='dob_required',
        ),
        migrations.RemoveField(
            model_name='geusersettings',
            name='email_required',
        ),
        migrations.RemoveField(
            model_name='geusersettings',
            name='gender_required',
        ),
        migrations.RemoveField(
            model_name='geusersettings',
            name='location_required',
        ),
        migrations.RemoveField(
            model_name='geusersettings',
            name='mobile_number_required',
        ),
        migrations.RemoveField(
            model_name='geusersettings',
            name='security_questions_required',
        ),
        migrations.RemoveField(
            model_name='geusersettings',
            name='show_email_field',
        ),
        migrations.RemoveField(
            model_name='geusersettings',
            name='show_mobile_number_field',
        ),
        migrations.RemoveField(
            model_name='geusersettings',
            name='show_security_question_fields',
        ),
    ]
