# Generated by Django 3.1.13 on 2021-12-28 13:13

import wagtail.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='thank_you_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
