# Generated by Django 3.1.13 on 2021-12-27 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('articles', '0002_footerindexpage_footerpage_sectionindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionpage',
            name='css_color',
            field=models.TextField(blank=True, default='', help_text='CSS color that should be applied to this section', null=True),
        ),
        migrations.AddField(
            model_name='sectionpage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
