# Generated by Django 3.1.14 on 2022-01-13 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('articles', '0004_articlepage_feature_in_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
