# Generated by Django 4.0.2 on 2022-03-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_articlepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
