# Generated by Django 4.0.3 on 2022-03-20 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailmedia", "0004_duration_optional_floatfield"),
        ("articles", "0008_alter_articlepage_subtitle"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlepage",
            name="featured_media",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailmedia.media",
            ),
        ),
    ]
