# Generated by Django 4.0.2 on 2022-05-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_articlepage_featured_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='hide_comment',
            field=models.BooleanField(default=False, help_text='Check if we need to hide the comments on the article.'),
        ),
    ]
