# Generated by Django 4.0.2 on 2022-06-02 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_articlepage_hide_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepage',
            name='hide_comment',
        ),
    ]
