# Generated by Django 3.1.13 on 2021-12-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='theme',
            field=models.CharField(blank=True, choices=[('a-custom-theme', 'An example theme'), ('default', 'Default'), ('springster-theme', 'Springster theme'), ('zathu-theme', 'Zathu theme')], db_index=True, max_length=100, null=True, verbose_name='theme'),
        ),
    ]
