# Generated by Django 3.1.14 on 2021-12-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='theme',
            field=models.CharField(blank=True, choices=[('default', 'Default'), ('ninyampinga-theme', 'Ninyampinga theme'), ('springster-theme', 'Springster theme'), ('yegna-theme', 'Yegna theme'), ('zathu-theme', 'Zathu theme')], db_index=True, max_length=100, null=True, verbose_name='theme'),
        ),
    ]
