# Generated by Django 3.1.14 on 2022-01-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='theme',
            field=models.CharField(blank=True, choices=[('ninyampinga', 'NiNyampinga theme'), ('springster', 'Springster theme'), ('tujibebe', 'Tujibebe theme'), ('yegna', 'Yegna theme'), ('zathu', 'Zathu theme')], db_index=True, max_length=100, null=True, verbose_name='theme'),
        ),
    ]
