# Generated by Django 3.1.14 on 2022-01-21 17:58

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220113_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='social_media_links_on_footer_page',
            field=wagtail.core.fields.StreamField([('social_media_site', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=True)), ('link', wagtail.core.blocks.CharBlock(required=True)), ('image', wagtail.images.blocks.ImageChooserBlock())]))], blank=True, null=True),
        ),
    ]
