# Generated by Django 3.1.14 on 2021-12-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20211229_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='theme',
            field=models.CharField(blank=True, choices=[('default', 'Default'), ('ninyampinga', 'Ninyampinga theme'), ('springster', 'Springster theme'), ('yegna', 'Yegna theme'), ('zathu', 'Zathu theme')], db_index=True, max_length=100, null=True, verbose_name='theme'),
        ),
    ]
