# Generated by Django 4.0.3 on 2022-03-21 06:03

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_sitesettings_fb_enable_chat_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='banners',
            field=wagtail.core.fields.StreamField([('banner', wagtail.core.blocks.StructBlock([('banner_image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('banner_link_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('banner_external_link', wagtail.core.blocks.URLBlock(required=False))]))], blank=True, null=True),
        ),
    ]
