# Generated by Django 4.0.3 on 2022-03-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_homepage_banners'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='featured_articles',
            field=models.TextField(blank=True, default=15, help_text='featured articles', null=True),
        ),
    ]
