# Generated by Django 4.0.3 on 2022-03-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_homepage_featured_articles"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="moderator_reply_name",
            field=models.TextField(
                blank=True,
                default="BigSis",
                help_text="The name that will appear on the moderator comment reply. Default is BigSis",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="featured_articles",
            field=models.TextField(
                blank=True,
                default=15,
                help_text="The number of featured articles on the Home Page. Default is 15",
                null=True,
            ),
        ),
    ]
