# Generated by Django 4.0.3 on 2022-03-31 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_homepage_featured_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='moderator_reply_name',
            field=models.CharField(blank=True, default='BigSis', help_text='The name that will appear on the moderator comment reply. Default is BigSis', max_length=100, null=True, verbose_name='moderator'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='featured_articles',
            field=models.TextField(blank=True, default=15, help_text='The number of featured articles on the Home Page. Default is 15', null=True),
        ),
    ]
