# Generated by Django 4.0.3 on 2022-03-31 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_homepage_moderator_reply_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='moderator_reply_name',
            field=models.CharField(blank=True, default='BigSis', help_text='The name that will appear on the moderator comment reply. Default is BigSis', max_length=100, null=True, verbose_name='moderator'),
        ),
    ]
