# Generated by Django 4.0.3 on 2022-03-31 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_sitesettings_moderator_reply_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='commenting_switch',
            field=models.BooleanField(default=True, verbose_name='commenting'),
        ),
    ]
