# Generated by Django 4.0.3 on 2022-04-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_sitesettings_moderator_reply_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='comment_posting',
            field=models.BooleanField(default=True, help_text='Allow users to submit new comments', verbose_name='Allow comment posting'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_comments',
            field=models.BooleanField(default=True, help_text='Show existing user comments, if disabled, this will disable new comment submission.', verbose_name='Show existing comments'),
        ),
    ]
