# Generated by Django 4.0.3 on 2022-04-04 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('home', '0011_sitesettings_commenting_switch'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='terms_and_conditions',
            field=models.ForeignKey(blank=True, help_text='Choose the terms & conditions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
    ]
