# Generated by Django 4.0.3 on 2022-03-31 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_homepage_moderator_reply_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='moderator_reply_name',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='moderator_reply_name',
            field=models.CharField(blank=True, default='BigSis', help_text='The name that will appear on the moderator comment reply. Default is BigSis', max_length=100, null=True, verbose_name='moderator'),
        ),
    ]
