# Generated by Django 4.0.3 on 2022-05-11 13:47

import wagtail.core.blocks
import wagtail.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_sitesettings_comment_posting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='allowed_emails',
            field=wagtail.core.fields.StreamField([('email_address', wagtail.core.blocks.EmailBlock())], blank=True, null=True),
        ),
    ]
